package com.yunde.website.allpay.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("operators", "id", Operator.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_resources", "id", SysResource.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_menu", "id", SysRoleMenu.class);
		arp.addMapping("sys_role_resource", "id", SysRoleResource.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_menu", "id", SysUserMenu.class);
		arp.addMapping("sys_user_resource", "id", SysUserResource.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
	}
}

