package com.yunde.website.allpay.common.model;

import com.yunde.website.allpay.common.model.base.BaseOperator;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operator extends BaseOperator<Operator> {
	public static final Operator dao = new Operator();

	public Set<Enum<?>> cacheSet() {
		return new HashSet<Enum<?>>(){{
			add(c.openId);
		}};
	}
}
