package com.yunde.website.allpay.common.model;

import com.jfinal.kit.StrKit;
import com.yunde.website.allpay.common.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu();

	@Override
	protected boolean beforeSave() {
		setIsNull(c.id, this.getParentId().concat("-").concat(StrKit.createNoncestr(6)));
		return super.beforeSave();
	}
}
