package com.yunde.website.allpay.common.model;

import com.allpay.common.model.base.BaseSysRole;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole();

	@Override
	protected boolean beforeSave() {
		this.setId(StrKit.uuidNoneLine());
		return super.beforeSave();
	}
}
