package com.yunde.website.allpay.common.model;

import com.jfinal.kit.StrKit;
import com.yunde.website.allpay.common.model.base.BaseSysResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysResource extends BaseSysResource<SysResource> {
	public static final SysResource dao = new SysResource();

	@Override
	protected boolean beforeSave() {
		this.setId(StrKit.uuidNoneLine());
		return super.beforeSave();
	}
}
