package com.yunde.website.allpay.common.model;

import com.allpay.common.model.base.BaseSysRoleResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleResource extends BaseSysRoleResource<SysRoleResource> {
	public static final SysRoleResource dao = new SysRoleResource();
}
