package com.yunde.website.allpay.common.model;

import com.allpay.common.model.base.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole();
}
