package com.yunde.website.allpay.common.model;

import com.yunde.website.allpay.common.model.base.BaseSysUserMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserMenu extends BaseSysUserMenu<SysUserMenu> {
	public static final SysUserMenu dao = new SysUserMenu();
}
