package com.yunde.website.allpay.common.model;

import com.yunde.website.allpay.common.model.base.BaseSysUserResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserResource extends BaseSysUserResource<SysUserResource> {
	public static final SysUserResource dao = new SysUserResource();
}
