package com.yunde.website.allpay.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUserResource<M extends BaseSysUserResource<M>> extends Model<M> implements IBean {

	public static enum c {
		id,
		userId,
		resourceId,
	}

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setUserId(String userId) {
		set("userId", userId);
		return (M)this;
	}

	public String getUserId() {
		return getStr("userId");
	}

	public M setResourceId(String resourceId) {
		set("resourceId", resourceId);
		return (M)this;
	}

	public String getResourceId() {
		return getStr("resourceId");
	}

}
