package com.yunde.website.allpay.common.model.base;

import com.jfinal.ext.model.RedisUnionAttrModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOperator<M extends BaseOperator<M>> implements IBean {

	public static enum c {
		id,
		openId,
		realName,
		phone,
		remark,
		createTime,
		createUser,
	}

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}

	public String getOpenId() {
		return getStr("openId");
	}

	public M setRealName(String realName) {
		set("realName", realName);
		return (M)this;
	}

	public String getRealName() {
		return getStr("realName");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}

	public M setCreateUser(String createUser) {
		set("createUser", createUser);
		return (M)this;
	}

	public String getCreateUser() {
		return getStr("createUser");
	}

}
