package com.yunde.website.allpay.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRoleMenu<M extends BaseSysRoleMenu<M>> extends Model<M> implements IBean {

	public static enum c {
		id,
		roleId,
		menuId,
	}

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setRoleId(String roleId) {
		set("roleId", roleId);
		return (M)this;
	}

	public String getRoleId() {
		return getStr("roleId");
	}

	public M setMenuId(String menuId) {
		set("menuId", menuId);
		return (M)this;
	}

	public String getMenuId() {
		return getStr("menuId");
	}

}
