package com.yunde.website.allpay.common.model.base;

import com.jfinal.ext.model.RedisModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends RedisModel<M> implements IBean {

	public static enum c {
		id,
		type,
		name,
		menuType,
		icon,
		link,
		state,
		orderNo,
		parentId,
		createUser,
		createTime,
	}

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}

	public String getType() {
		return getStr("type");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setMenuType(String menuType) {
		set("menuType", menuType);
		return (M)this;
	}

	public String getMenuType() {
		return getStr("menuType");
	}

	public M setIcon(String icon) {
		set("icon", icon);
		return (M)this;
	}

	public String getIcon() {
		return getStr("icon");
	}

	public M setLink(String link) {
		set("link", link);
		return (M)this;
	}

	public String getLink() {
		return getStr("link");
	}

	public M setState(String state) {
		set("state", state);
		return (M)this;
	}

	public String getState() {
		return getStr("state");
	}

	public M setOrderNo(Integer orderNo) {
		set("orderNo", orderNo);
		return (M)this;
	}

	public Integer getOrderNo() {
		return getInt("orderNo");
	}

	public M setParentId(String parentId) {
		set("parentId", parentId);
		return (M)this;
	}

	public String getParentId() {
		return getStr("parentId");
	}

	public M setCreateUser(String createUser) {
		set("createUser", createUser);
		return (M)this;
	}

	public String getCreateUser() {
		return getStr("createUser");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}

}
