package com.yunde.website.allpay.common.model.base;

import com.jfinal.ext.model.RedisModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends RedisModel<M> implements IBean {

	public static enum c {
		id,
		name,
		parentId,
		remark,
		state,
	}

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setParentId(String parentId) {
		set("parentId", parentId);
		return (M)this;
	}

	public String getParentId() {
		return getStr("parentId");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setState(String state) {
		set("state", state);
		return (M)this;
	}

	public String getState() {
		return getStr("state");
	}

}
