package com.yunde.website.allpay.common.model.base;

import com.jfinal.ext.model.RedisModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends RedisModel<M> implements IBean {

	public static enum c {
		id,
		name,
		image,
		account,
		state,
		password,
		phone,
		email,
		nickName,
	}

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setImage(String image) {
		set("image", image);
		return (M)this;
	}

	public String getImage() {
		return getStr("image");
	}

	public M setAccount(String account) {
		set("account", account);
		return (M)this;
	}

	public String getAccount() {
		return getStr("account");
	}

	public M setState(String state) {
		set("state", state);
		return (M)this;
	}

	public String getState() {
		return getStr("state");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}

	public String getPassword() {
		return getStr("password");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}

	public String getEmail() {
		return getStr("email");
	}

	public M setNickName(String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public String getNickName() {
		return getStr("nickName");
	}

}
