package com.yunde.website.allpay.common.model.base;

import com.jfinal.ext.model.RedisModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysResource<M extends BaseSysResource<M>> extends RedisModel<M> implements IBean {

	public static enum c {
		id,
		resFor,
		resType,
		resName,
		resValue,
		state,
		orderNo,
		parentId,
		remark,
		createUser,
		createTime,
	}

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setResFor(String resFor) {
		set("resFor", resFor);
		return (M)this;
	}

	public String getResFor() {
		return getStr("resFor");
	}

	public M setResType(String resType) {
		set("resType", resType);
		return (M)this;
	}

	public String getResType() {
		return getStr("resType");
	}

	public M setResName(String resName) {
		set("resName", resName);
		return (M)this;
	}

	public String getResName() {
		return getStr("resName");
	}

	public M setResValue(String resValue) {
		set("resValue", resValue);
		return (M)this;
	}

	public String getResValue() {
		return getStr("resValue");
	}

	public M setState(String state) {
		set("state", state);
		return (M)this;
	}

	public String getState() {
		return getStr("state");
	}

	public M setOrderNo(Integer orderNo) {
		set("orderNo", orderNo);
		return (M)this;
	}

	public Integer getOrderNo() {
		return getInt("orderNo");
	}

	public M setParentId(String parentId) {
		set("parentId", parentId);
		return (M)this;
	}

	public String getParentId() {
		return getStr("parentId");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setCreateUser(String createUser) {
		set("createUser", createUser);
		return (M)this;
	}

	public String getCreateUser() {
		return getStr("createUser");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}

}
