package com.yunde.website.allpay.api;

//import com.allpaycloud.base.cloud.plugin.allpay.AllpayModulePlugin;
import com.yunde.website.allpay.base.plugin.allpay.AllpayModulePlugin;

/**
 * Generated by Allpay, do not modify this file.
 */
public class _BasicModuleMappingKit {
    public static void mapping(AllpayModulePlugin plugin){
//        plugin.add(CustomerModule.class);
//        plugin.add(DeviceModule.class);
//        plugin.add(DictModule.class);
//        plugin.add(FactoryModule.class);
//        plugin.add(ProducerModule.class);
//        plugin.add(PropAddressModule.class);
//        plugin.add(PropHierarchyModule.class);
//        plugin.add(ProprietorModule.class);
    }
}
