package com.yunde.website.allpay.api;

//import com.allpaycloud.base.cloud.plugin.allpay.AllpayModulePlugin;
import com.yunde.website.allpay.base.plugin.allpay.AllpayModulePlugin;

/**
 * Generated by Allpay, do not modify this file.
 */
public class _ModuleMappingKit {
    public static void mapping(AllpayModulePlugin plugin){
//        plugin.add(BillModule.class);
//        plugin.add(CmbcNetTradePlatformModule.class);
//        plugin.add(CustomerFamilyModule.class);
//        plugin.add(DeviceOnOffModule.class);
//        plugin.add(DevicePushModule.class);
//        plugin.add(DeviceShipmentModule.class);
//        plugin.add(PassthroughModule.class);
//        plugin.add(PayoffModule.class);
//        plugin.add(PropFamilyModule.class);
//        plugin.add(RateModule.class);
//        plugin.add(ThemeModule.class);
        //自定义mapping设置，满足子系统分离需求
        _DiyMappingKit.mapping(plugin);
    }
}
