package com.yunde.website.allpay.api;

import com.yunde.website.allpay.base.plugin.allpay.AbsAllpayModule;
import com.yunde.website.allpay.base.plugin.allpay.AllpayModuleTable;
import com.yunde.website.allpay.base.plugin.allpay.AllpayServiceBind;

/**
 * Generated by Allpay, do not modify this file.
 */
@AllpayServiceBind(service = "dict2Service")
public class DictModule extends AbsAllpayModule {
    public final static DictModule me = new DictModule();

    public AllpayModuleTable bankBranch = new AllpayModuleTable(this, "BankBranch");
    public AllpayModuleTable dict = new AllpayModuleTable(this, "Dict");
    public AllpayModuleTable dictDetail = new AllpayModuleTable(this, "DictDetail");
    public AllpayModuleTable dictJs = new AllpayModuleTable(this, "DictJs");
    public AllpayModuleTable viewType = new AllpayModuleTable(this, "ViewType");
    public AllpayModuleTable viewTypeWhiteList = new AllpayModuleTable(this, "ViewTypeWhiteList");

    public enum business{
        setBatchDictDetailBus,
    }
}
